### ISSUE TITLE
Bahçeşehir Üniversitesi Yazılım Mühendisliği

### ISSUE THREAD

**Issue by Hasangokcee** [kahyalar/ama#2]
Bahçeşehir Üniversitesi Yazılım Mühendisliği bölümünü istiyorum az önce yazınızı okudum okul hakkında çok açıklayıcı oldu fakat derslerin hepsinin ingilizce olduğundan bahsetmişsiniz ingilizcesi çok iyi olmayan biri sizce bunu halledebilir mi?

**Comment by kahyalar** [comment]
Merhaba,

Üniversitenin B2 İngilizce yeterlilik koşulu var zaten. Olur da hazırlık sınavını geçemezseniz, öncelikle sizi İngilizce hazırlık okuluna alıyorlar. Yani bir nevi, İngilizceniz o seviyeye gelmeden bölüme başlamıyorsunuz.
