### ISSUE TITLE
Estonya`da iş bulmak için kendimi ne kadar geliştirmeliyim?

### ISSUE THREAD

**Issue by aproto4** [kahyalar/ama#3]
Selam Furkan hocam. 

Hocam, uzun zamandır(5-6 yıl kadar) web programlama ile ilgileniyorum ve son 2 yıl ise web güvenliği ile uğraşıyorum.  Aslında güvenliğin bir çok alanıyla ilgiliyim fakat tabiri caizse kendimi uzman gördüğüm alan web`in güvenlik kısmı . Kariyer planım güvenlik alanında uzmanlaşmak ama şu an her şeyle ilgileniyorum(yazılım programlama dilleri filan ve güvenlik). İki alanı da çok seviyorum ve ilgileniyorum. 

Daha önce bu alanda çalışmadım(CV`ye yazacak tecrübem yok) ve bilgisayar ile ilgili bir eğitimim de olmadı maalesef. Bu işi yıllardır sevdiğim için yapıyorum. Şimdi ise yurtdışında çalışmak istiyorum ve fark ettim de tecrübe kısmında hiç kendimi geliştirmedim sadece teorik olarak öğrendim. Proje yapmaya daha çok vakit ayırmayı planlıyorum. 
Siz bu konuda ne düşünüyorsunuz?
Benim gibi iş tecrübesi olmayan biri Estonya gibi bir ülkede çalışmak için neler yapmalıyım ve daha çok nelere dikkat etmeliyim?
Bu arada Ingilizce seviyem B2.

Cevaplarsanız çok memnun olurum, 
Teşekkür ederim, Saygılar

**Comment by kahyalar** [comment]
Selamlar @aproto4,

Yani sadece Estonya üzerinde düşünmekten öte, güvenliğin bir güzel yanı da uluslararası certifikasyon alabilirseniz onlar da emin olun projeler/ürünler/iş tecrübeleri kadar etkili. Tabi ki bir yandan open source projelere de vakit ayırırsan (mesela GitHub gibi bir mecrada) insanlara da gösterebileceğin bir portfolyon olur.

E tabi İngilizce'nin önemi çok büyük, ki B2 oluşunun da artısı oldukça büyük olacaktır. 

Ekstra bir sorun olursa, issue'ya ekleyebilirsin.

Saygılar,
Furkan
